import React, { useMemo, useState } from 'react';
import { INITIAL_TEST_CASES, getTestMatrixSummary } from '../../data/testingMatrixData';
import { TestCaseItem, TestMatrixSummary } from '../../types/testing';
import { CheckSquare, CheckCircle2, XCircle, AlertOctagon, ExternalLink, Filter, CircleSlash } from 'lucide-react';

export const TestingMatrixView: React.FC = () => {
  const [testCases] = useState<TestCaseItem[]>(INITIAL_TEST_CASES);
  const [filterCategory, setFilterCategory] = useState('ALL');
  const [filterStatus, setFilterStatus] = useState('ALL');
  const summary: TestMatrixSummary = useMemo(() => getTestMatrixSummary(testCases), [testCases]);
  const categories = ['ALL', 'UNIT', 'STRATEGY', 'BACKTEST_CORRECTNESS', 'RISK_ENGINE', 'DUPLICATE_ORDER', 'DATA_VALIDATION', 'STALE_DATA', 'API_FAILURE', 'NETWORK_FAILURE', 'SECURITY', 'AUTHORIZATION', 'KILL_SWITCH', 'BROKER_ADAPTER'];
  const filteredCases = testCases.filter(tc => (filterCategory === 'ALL' || tc.category === filterCategory) && (filterStatus === 'ALL' || tc.status === filterStatus));

  return <div className="space-y-6">
    <div className="bg-slate-900 border border-slate-800 rounded-lg p-5 flex flex-wrap justify-between items-center gap-4"><div><div className="flex items-center space-x-2"><CheckSquare className="w-5 h-5 text-emerald-400" /><h2 className="text-sm font-semibold text-slate-100">Verification & Test Suite Matrix</h2></div><p className="text-xs text-slate-400 mt-1">The matrix documents required assertions. Executable smoke tests now run in CI; this screen does not fabricate PASS results.</p></div><a href="https://github.com/smurari229-ai/QuantPulse/actions" target="_blank" rel="noreferrer" className="flex items-center space-x-1.5 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded text-xs font-mono font-semibold"><ExternalLink className="w-3.5 h-3.5" /><span>Open CI Runs</span></a></div>
    <div className="grid grid-cols-2 md:grid-cols-6 gap-3 font-mono text-xs"><div className="bg-slate-900 border border-slate-800 rounded-lg p-3.5"><span className="text-slate-400 text-[10px] block mb-1">TOTAL</span><span className="text-xl font-bold text-slate-100">{summary.total}</span></div><div className="bg-slate-900 border border-slate-800 rounded-lg p-3.5"><span className="text-slate-400 text-[10px] block mb-1">DOCUMENTED PASS</span><span className="text-xl font-bold text-emerald-400">{summary.passed}</span></div><div className="bg-slate-900 border border-slate-800 rounded-lg p-3.5"><span className="text-slate-400 text-[10px] block mb-1">FAIL</span><span className="text-xl font-bold text-rose-400">{summary.failed}</span></div><div className="bg-slate-900 border border-slate-800 rounded-lg p-3.5"><span className="text-slate-400 text-[10px] block mb-1">BLOCKED</span><span className="text-xl font-bold text-amber-400">{summary.blocked}</span></div><div className="bg-slate-900 border border-slate-800 rounded-lg p-3.5"><span className="text-slate-400 text-[10px] block mb-1">NOT RUN</span><span className="text-xl font-bold text-slate-300">{summary.notRun}</span></div><div className="bg-slate-900 border border-slate-800 rounded-lg p-3.5"><span className="text-slate-400 text-[10px] block mb-1">DOCUMENTED PASS %</span><span className="text-xl font-bold text-slate-100">{summary.passPercentage}%</span></div></div>
    <div className="bg-slate-900 border border-slate-800 rounded-lg p-3.5 flex flex-wrap justify-between items-center gap-3 text-xs font-mono"><div className="flex items-center space-x-2"><Filter className="w-4 h-4 text-slate-500" /><span className="text-slate-400">Category:</span><select value={filterCategory} onChange={e => setFilterCategory(e.target.value)} className="bg-slate-950 border border-slate-800 rounded px-2.5 py-1 text-slate-200">{categories.map(c => <option key={c}>{c}</option>)}</select></div><div className="flex items-center space-x-1.5"><span className="text-slate-400">Status:</span>{['ALL','PASS','FAIL','BLOCKED','NOT_RUN'].map(st => <button key={st} onClick={() => setFilterStatus(st)} className={`px-2 py-0.5 rounded text-[10px] ${filterStatus === st ? 'bg-blue-600 text-white font-bold' : 'bg-slate-800 text-slate-400'}`}>{st}</button>)}</div></div>
    <div className="bg-slate-900 border border-slate-800 rounded-lg overflow-hidden font-mono text-xs"><div className="px-4 py-2.5 bg-slate-950/40 border-b border-slate-800 flex justify-between text-[11px] text-slate-400"><span>Displaying {filteredCases.length} assertions</span><span>Executable CI suite is authoritative</span></div><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-950/60 text-slate-400 border-b border-slate-800"><tr><th className="px-4 py-2.5">ID</th><th className="px-4 py-2.5">CATEGORY</th><th className="px-4 py-2.5">TEST</th><th className="px-4 py-2.5">STATUS</th><th className="px-4 py-2.5">EXPECTED</th><th className="px-4 py-2.5">REASON</th></tr></thead><tbody className="divide-y divide-slate-800/60 text-slate-300">{filteredCases.map(tc => <tr key={tc.id}><td className="px-4 py-3 font-bold text-slate-400">{tc.id}</td><td className="px-4 py-3">{tc.category}</td><td className="px-4 py-3 font-bold text-slate-100">{tc.name}</td><td className="px-4 py-3">{tc.status === 'PASS' ? <span className="flex items-center gap-1 text-emerald-400 font-bold"><CheckCircle2 className="w-3 h-3" />PASS (DOCUMENTED)</span> : tc.status === 'FAIL' ? <span className="flex items-center gap-1 text-rose-400 font-bold"><XCircle className="w-3 h-3" />FAIL</span> : tc.status === 'BLOCKED' ? <span className="flex items-center gap-1 text-amber-400 font-bold"><AlertOctagon className="w-3 h-3" />BLOCKED</span> : <span className="flex items-center gap-1 text-slate-400 font-bold"><CircleSlash className="w-3 h-3" />NOT RUN</span>}</td><td className="px-4 py-3 text-[11px] text-slate-400">{tc.expectedBehavior}</td><td className="px-4 py-3 text-[11px]">{tc.status === 'BLOCKED' ? tc.blockingReason : tc.assertionMessage}</td></tr>)}</tbody></table></div></div>
  </div>;
};
